name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  use-checkout-and-build:
    uses: MuhammadWara/ChatApp/.github/workflows/checkout-and-build.yml@master

  additional-steps:
    runs-on: ubuntu-latest
    needs: use-checkout-and-build  
    steps:
      - name: check repo is checked out or not 
        run: |
          ls -lah    
      - name: Run tests
        run: npm test

