name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  use-checkout:
    uses: ./.github/workflows/checkout-workflow.yml

  additional-steps:
    runs-on: ubuntu-latest
    needs: use-checkout  # Ensures this job runs after the checkout job
    steps:
      - name: Display current directory
        run: pwd

      - name: List files
        run: ls -la
