name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  use-checkout-and-build:
    uses: ./.github/workflows/checkout-and-build.yml

  additional-steps:
    runs-on: ubuntu-latest
    needs: use-checkout-and-build  
    steps:
      - name: Run tests
        run: npm test

      - name: Deploy
        run: |
          ls -lah
