name: Custom Run Number Workflow

on:
  push:
    branches:
      - master
      - develop

jobs:
  set-run-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get last run number
        id: get_last_run
        run: |
          BRANCH_NAME="${{ github.event.inputs.branch_name }}"
          echo "Branch Name: $BRANCH_NAME"

          # Define starting run numbers for each branch
          if [[ "$BRANCH_NAME" == "main" ]]; then
            STARTING_RUN_NUMBER=1
          elif [[ "$BRANCH_NAME" == "develop" ]]; then
            STARTING_RUN_NUMBER=101
          else
            echo "Unsupported branch: $BRANCH_NAME"
            exit 1
          fi

          # Fetch the last run number for the specified branch
          LAST_RUN_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=${BRANCH_NAME}&status=success" | \
            jq '.workflow_runs[0].run_number // 0')

          echo "Last Run Number: $LAST_RUN_NUMBER"

          # Calculate new run number
          if [ "$LAST_RUN_NUMBER" -eq 0 ]; then
            NEW_RUN_NUMBER=$STARTING_RUN_NUMBER
          else
            NEW_RUN_NUMBER=$((LAST_RUN_NUMBER + 1))
          fi

          echo "New Run Number: $NEW_RUN_NUMBER"
          echo "run_number=$NEW_RUN_NUMBER" >> $GITHUB_ENV

      - name: Set job name
        id: set_name
        run: echo "job_name=${{ github.event.inputs.branch_name }} #${{ env.run_number }}" >> $GITHUB_ENV

      - name: Print Run Number
        run: echo "Run Number is ${{ env.run_number }}"
